version: '3'
services:
  iris:
    image: "iris-server:v1"
    ports:
      - "3000:3000"
      - "8800:8800"
    networks:
      - chronicle
  chronicle:
    image: "chronicle-server:v1"
    #volumes:
    #  - /telos/chronicle-data:/chronicle-data
    networks:
      - chronicle

networks:
  chronicle:
      driver: bridge